name: Frontend Deployment to Alibaba Cloud - Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Alibaba Cloud
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }} # SSH 密码
          port: ${{ secrets.PORT }} # SSH 端口
          debug: true
          script: |
            echo "Installing pnpm..."
            npm install -g pnpm@latest
            echo "pnpm installed. Now installing dependencies..."
            pnpm i
            echo "Dependencies installed. Building..."
            pnpm run build
            echo "Build complete. Reloading Nginx..."
            sudo nginx -s reload # 注意：可能需要 sudo 来执行 nginx 命令